{% set name = "quetz" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-server/{{ name }}-server-{{ version }}.tar.gz
  sha256: 65ddb24451e6b0dc1c91544ce4b93fa800bc1ac4c951cdd6a2bcd13acd5e7723

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - quetz = quetz.cli:app

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - alembic
    - aiofiles
    - appdirs
    - authlib <1.0.0
    - fastapi
    - fsspec
    - h2
    - httpx >=0.22.0
    - importlib-metadata
    - itsdangerous
    - jinja2
    - pluggy
    - prometheus_client
    - python-multipart
    - pyyaml
    - requests
    - sqlalchemy
    - sqlalchemy-utils
    - tenacity
    - toml
    - typer
    - typing_extensions
    - ujson
    - uvicorn
    - xattr
    - zstandard
  run_constrained:
    - s3fs >=2021.10.1
    - adlfs >=2021.10.0
    - gcsfs >=2022.3.0

test:
  imports:
    - quetz
  commands:
    - quetz --help

about:
  home: https://github.com/mamba-org/quetz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Mamba package server

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
    - janjagusch
