{% set name = "quetz" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/quetz/archive/v{{ version }}.tar.gz
  sha256: b0dd139a7feab2170786b856c7a2fe30a76e7937d3c96396f724b2888fb54ab1

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - fastapi >=0,<1
    - authlib >=0,<1
    - httpx =0.12.0
    - sqlalchemy >=1,<2
    - sqlite >=3,<4
    - python-multipart >=0,<1
    - uvicorn >=0,<1
    - zstandard >=0,<1
    - conda-build >=3,<4

test:
  imports:
    - quetz

about:
  home: https://github.com/TheSnakePit/quetz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The Mamba package server'

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
