{% set name = "quetz" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/quetz/archive/v{{ version }}.tar.gz
  sha256: 0e38c98a590225c6973969aa87cdd8ae2a4224b94e99c6e6db46d0c76acc4e8e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - fastapi >=0,<1
    - authlib >=0,<1
    - httpx =0.12.0
    - sqlalchemy >=1,<2
    - sqlite >=3,<4
    - python-multipart >=0,<1
    - uvicorn >=0,<1
    - zstandard >=0,<1
    - conda-build >=3,<4
    - appdirs >=1,<2
    - toml >=0,<1

test:
  imports:
    - quetz
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/TheSnakePit/quetz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Mamba package server

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
