{% set name = "quetz" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/quetz/archive/refs/tags/v{{ version }}.tar.gz
  sha256: a5d4d1898ab7068ad1ec9ea5ae4a4a3f8eb5bfb754d0665b2254e6318d4fb126

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - quetz = quetz.cli:app

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - pip
    - fastapi >=0.65.0,<1.0
    - typer
    - authlib
    - httpx >=0.20.0
    - sqlalchemy <1.4.0
    - sqlalchemy-utils
    - sqlite
    - python-multipart
    - uvicorn
    - zstandard
    - appdirs
    - toml
    - fsspec
    - requests
    - h2 >3,<4.0.0
    - pluggy
    - jinja2
    - itsdangerous
    - alembic 1.*
    - tenacity
    - xattr
    - aiofiles
    - pyyaml
    - ujson
    - prometheus_client
    - pamela
    - typing_extensions
    - importlib-metadata >=4.8,<5
  run_constrained:
    - s3fs >=2021.10.1
    - adlfs >=2021.10.0
    - gcsfs >=2021.10.1

test:
  imports:
    - quetz
  commands:
    - quetz --help

about:
  home: https://github.com/mamba-org/quetz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Mamba package server

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
    - janjagusch
