{% set name = "quetz" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}-server/{{ name }}-server-{{ version }}.tar.gz
  sha256: 9097bfed3156a33e1da092db4e1ebb828107d077f80b4706ca2293009a1b6e9e

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - quetz = quetz.cli:app

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - alembic 1.*
    - aiofiles
    - appdirs
    - fastapi >=0.65.0,<1.0
    - fsspec
    - h2 >3,<4.0.0
    - importlib-metadata >=4.8,<5
    - itsdangerous
    - jinja2
    - pluggy
    - prometheus_client
    - python-multipart
    - pyyaml
    - requests
    - sqlalchemy
    - sqlalchemy-utils
    - tenacity
    - toml
    - typer
    - typing_extensions
    - ujson
    - uvicorn
    - xattr
    - authlib
    - zstandard
    - pamela
  run_constrained:
    - s3fs >=2021.10.1
    - adlfs >=2021.10.0
    - gcsfs >=2021.10.1

test:
  imports:
    - quetz
  commands:
    - quetz --help

about:
  home: https://github.com/mamba-org/quetz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The Mamba package server

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
    - janjagusch
