{% set name = "quetz" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mamba-org/quetz/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1b10eac5b3590e7c065df24770ed3c20eb9f8e5aa00b3b5b4185dfa44d089cff

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python>=3.7
    - pip
    - fastapi >=0.65.0,<1.0
    - typer
    - authlib
    - psycopg2
    - httpx 0.16.0
    - sqlalchemy <1.4.0
    - sqlalchemy-utils
    - sqlite
    - python-multipart
    - uvicorn
    - zstandard
    - appdirs
    - toml
    - fsspec
    - s3fs
    - requests
    - h2 >3,<4.0.0
    - pluggy
    - jinja2
    - itsdangerous
    - alembic 1.*
    - tenacity
    - xattr
    - aiofiles
    - pyyaml
    - ujson
    - prometheus_client
    - pamela
    - typing_extensions
    - adlfs

test:
  imports:
    - quetz

about:
  home: https://github.com/mamba-org/quetz
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'The Mamba package server'

extra:
  recipe-maintainers:
    - mariobuikhuizen
    - wolfv
